services:
  app:
    image: node:alpine
    container_name: node
    command: node app.js
    working_dir: /usr/src/app
    ports:
    - 3000:3000
    - 5173:5173
    volumes:
    - type: bind
      source: ./app
      target: /usr/src/app
    tty: true

